name: 'Papertrail: PR Title'
description: 'Validates the PR title against configured rules.'
inputs:
  manifest:
    description: 'Path to release config manifest'
    required: false
    default: '.papertrail.config.yml'
  version:
    description: 'Version of papertrail CLI to use (e.g. latest, v0.1.0)'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Validate PR title
      shell: bash
      run: |
        go run github.com/bnprtr/papertrail/cmd/papertrail@${{ inputs.version }} pr-title \
          --manifest "${{ inputs.manifest }}"

